### ISSUE TITLE
Bold

### ISSUE THREAD

**Issue by mrworkman** [hicknhack-software/semantic-colorizer#13]
Would be awesome if **Bold** worked, but the setting seems to be ignored on SemanticColorizer options.

**Comment by arBmind** [comment]
The entire syntax coloring and styling seems quite broken in the latest visual studio versions.

If anyone knows how to fix this - any hints are appreciated.

**Comment by loftum** [comment]
I struggled with this myself.

Bold **_does_** work. However, the problem seems to be a combination of how VS classifies symbols, and how `ClassificationFormatDefinition` are prioritized, and how properties (like `IsBold`) are overridden down the "format chain".

I had problems making extension methods bold. I could change the color, but not the font weight.

It seems like VS classifies methods (including extension methods) as `identifier`s, in addition to my own classification `extensionmethod`. VS would allow me to override the color, but would then "win" the classification contest, and let the `identifier`'s format set `IsBold=false` in the end.

One solution to override format for symbols that are also classified by VS, is to "reset" VS's format.
For instance, for `identifier` you could export a reset format like this:

```csharp
[Export(typeof(EditorFormatDefinition))]
[ClassificationType(ClassificationTypeNames = Microsoft.CodeAnalysis.Classification.ClassificationTypeNames.Identifier)]
[Name(TagTypes.Identifier)]
[UserVisible(false)] // does not show under Tools/Options/Fonts and colors
[Order(After = Priority.Default)]
internal class OverrideIdentifierFormatDefinition : ClassificationFormatDefinition
{
	public OverrideIdentifierFormatDefinition()
	{
		DisplayName = "Reset Identifier";
		ForegroundColor = null;
		IsBold = null;
		IsItalic = null;
	}
}
```

This will work for methods and the like. But it feels dirty, and might feel weird for the end-user.

I also tried to declare base type for my own ExtensionMethod ClassificationTypeDefinition:

```csharp
[Export(typeof(ClassificationTypeDefinition))]
[BaseDefinition(ClassificationTypeNames.Identifier)]
[Name(TagTypes.ExtensionMethd)]
public static ClassificationTypeDefinition ExtensionMethod;
```
...with no luck.


I think the right thing would be to tell VS that the extension method format is an identifier format, but a more specific one. But I haven't found a way to do that.

**Comment by loftum** [comment]
After a little fiddling, this seems to work, without resetting the identifier format:
To make extension methods bold (as an example):
- Set base definition for ExtensionMethodType to ClassificationTypeNames.Identifier.
- Set order for SemanticExtensionMethodFormat After=ClassificationTypeNames.Identifier.

Like this:

```csharp
[Export(typeof(ClassificationTypeDefinition))]
//
// Set base definition
//
[BaseDefinition(Microsoft.VisualStudio.Text.Classification.ClassificationTypeNames.Identifier)]
[Name(Constants.ExtensionMethodFormat)]
internal static ClassificationTypeDefinition ExtensionMethodType;
```


```csharp
[Export(typeof(EditorFormatDefinition))]
[ClassificationType(ClassificationTypeNames = Constants.ExtensionMethodFormat)]
[Name(Constants.ExtensionMethodFormat)]
[UserVisible(true)]
//
// [Order(After = Priority.Default)] // Remove this
// Order after identifier
//
[Order(After = Microsoft.VisualStudio.Text.Classification.ClassificationTypeNames.Identifier)]
internal sealed class SemanticExtensionMethodFormat : ClassificationFormatDefinition
{
  public SemanticExtensionMethodFormat() {
    DisplayName = "Semantic Extension Method";
    IsBold = true;
  }
}
```

**Comment by arBmind** [comment]
Thank you @loftum 
I did some tests. It seems to me that adding `Order(After = "identifier")` is sufficient.

Do you had any issues with that?

**Comment by arBmind** [comment]
Version 1.3.1 contains this.

Please let me know if it works.

**Comment by arBmind** [comment]
ok, seems to work…
