### ISSUE TITLE
Property public word color

### ISSUE THREAD

**Issue by CedricBaetens** [hicknhack-software/semantic-colorizer#19]
When setting a color for a property the word 'public' will be colored in the same color.  This only happens with a property, not with any other variable, method etc..

**Comment by arBmind** [comment]
Thank you for reporting this. I will investigate.

**Comment by Liminiens** [comment]
@arBmind i think the bug is due to [keyword info leak from roslyn](https://github.com/hicknhack-software/semantic-colorizer/blob/develop/SemanticColorizer/SemanticColorizer.cs#L90) in my pr. It's actualy unused and if we remove it, the check here will be also redundant [here](https://github.com/hicknhack-software/semantic-colorizer/blob/develop/SemanticColorizer/SemanticColorizer.cs#L237).

I tried the changes above and it seems to not break things (in VS 2017 15.7):
![image](https://user-images.githubusercontent.com/10695322/39994321-95536ea4-5781-11e8-94b3-2e5f1203790f.png)

**Comment by arBmind** [comment]
should be fixed
